services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    ports:
      - "5432:5432"

  worker:
    build: .
    command: celery -A app.core.worker_config.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - web
      - redis

  redis:
    image: redis:7


volumes:
  postgres_data: